title: Andrew Bevan
author:
  name: Andrew Bevan
  email: bluntspoon@gmail.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Andrew Bevan on Code, Technology and Life.

# Build settings

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

minima:
  skin: dark
  date_format: "%b %-d, %Y"

  # Generate social links in footer.
  #
  social_links:
     - { platform: twitter,        user_url: "https://twitter.com/bluntspoon" }
     - { platform: linkedin,       user_url: "https://www.linkedin.com/in/andrew-bevan" }
     - { platform: github,         user_url: "https://github.com/bluntspoon" }
     - { platform: telegram,       user_url: "https://t.me/bluntspoon" }
  #   - { platform: devto,          user_url: "https://dev.to/jekyll" }
  #   - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
  #   - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
  #   - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
  #   - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  #   - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
  #   - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
header_pages:
   - about.md
   - lists.md
   - blog.md

# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false

google_analytics: UA-12923011-8
