title: Andrew Bevan | Coding, Technology and Life
author:
  name: Andrew Bevan
  email: bluntspoon@gmail.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Andrew Bevan on Coding, Technology and Life.

# Build settings

# theme: minima
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist

# Theme-specific settings

minima:
  skin: auto
  date_format: "%-d %b %Y"

  # Generate social links in footer.
  #
  social_links:
     - platform: linkedin
       user_url: "https://www.linkedin.com/in/andrew-bevan"
     - platform: twitter
       user_url: "https://x.com/bluntspoon"
     - platform: github
       user_url: "https://github.com/bluntspoon"

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
header_pages:
    - about.md
    - lists.md
    - blog.md

# Set to `true` to show excerpts on the homepage.
# show_excerpts: false

google_analytics: G-VTF49EX4MD
