title: Andrew Bevan
author: bluntspoon
email: bluntspoon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Andrew Bevan on Web, Code, Technology and Life

twitter_username: bluntspoon
github_username:  bluntspoon

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
